export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const LOAD_CART = 'LOAD_CART';
export const PURCHASED = 'PURCHASED';
export const INIT_PURCHASING = 'INIT_PURCHASING';
export const PURCHASING_FAILED = 'PURCHASING_FAILED';
export const PURCHASING_SUCCESSFULLY = 'PURCHASING_SUCCESSFULLY';